### ISSUE TITLE
How Could I Convert the Output of TokenHMR to AMASS Format or HumanML3D format?

### ISSUE THREAD

**Issue by MD-Student** [saidwivedi/TokenHMR#22]
Hello, thanks for your great work. Human Reconstruction results are pretty good on images and videos. Now I wonder how to convert the output of TokenHMR back to AMASS format?
B
I could get the **pred_smpl_params** and **keypoints_3d** from the out of the model. But the shape of keypoints_3d are (N,**44**,3), rather than the shape of AMASS **joints** format which is (N,24,3). How can I get the (N,24,3) joints data from TokenHMR output?

**Comment by ouyangfeng2022** [comment]
Change [this line](https://github.com/saidwivedi/TokenHMR/blob/198645f7784a27a4df0eac32478b1e7bc3e13574/tokenhmr/lib/models/smpl_wrapper.py#L32C10-L32C13) to `joints = smpl_output.joints,` and the shape of keypoints_3d will be (N,64,3), of which the first 24 joints are what you need.

**Comment by Peilun818** [comment]
Hi, I notice you have finished this Human Reconstruction on images and videos. I achieved on images but not in video. When I run the last code: python tokenhmr/track.py \
    video.source=demo_sample/video/gymnasts.mp4 \
    render.colors=slahmr \
    +checkpoint=data/checkpoints/tokenhmr_model_latest.ckpt \
    +model_config=data/checkpoints/model_config.yaml

It always showed:
Error executing job with overrides: ['video.source=demo_sample/video/gymnasts.mp4', 'render.colors=slahmr', '+checkpoint=data/checkpoints/tokenhmr_model_latest.ckpt', '+model_config=data/checkpoints/model_config.yaml']
Traceback (most recent call last):
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 68, in main
    phalp_tracker = PHALP_Prime_TokenHMR(cfg)
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 50, in __init__
    super().__init__(cfg)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 53, in __init__
    self.setup_hmr()
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 53, in setup_hmr
    self.HMAR = TokenHMRPredictor(self.cfg)
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 21, in __init__
    super().__init__(cfg)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/models/hmar/hmr.py", line 17, in __init__
    self.load_weights(cfg.hmr.hmar_path)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/models/hmar/hmr.py", line 23, in load_weights
    self.hmar_old.load_weights(path)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/models/hmar/hmar.py", line 47, in load_weights
    checkpoint_file = torch.load(path)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Do you have similar problems or any clues to handle them? Sorry for bothering, cause it is a little hurried! I would appreciate it if you could reply to me.

Best regards,
Peilun
