### ISSUE TITLE
It seems some source files were missed

### ISSUE THREAD

**Issue by polwer** [saidwivedi/TokenHMR#4]
When I ran track.py and demo.py then I got an error:
from lib.models import load_tokenhmr
ModuleNotFoundError: No module named 'lib'
I searched the 'load_tokenhmr' in all files and got no definition,also without a folder named 'lib' and a source file named 'model'.

**Comment by saidwivedi** [comment]
Thanks for trying out the code. You are right about missing files. It should be fixed by now.

**Comment by Peilun818** [comment]
Hi, I notice you have finished this Human Reconstruction on images and videos. I achieved on images but not in video. When I run the last code: python tokenhmr/track.py \
    video.source=demo_sample/video/gymnasts.mp4 \
    render.colors=slahmr \
    +checkpoint=data/checkpoints/tokenhmr_model_latest.ckpt \
    +model_config=data/checkpoints/model_config.yaml

It always showed:
Error executing job with overrides: ['video.source=demo_sample/video/gymnasts.mp4', 'render.colors=slahmr', '+checkpoint=data/checkpoints/tokenhmr_model_latest.ckpt', '+model_config=data/checkpoints/model_config.yaml']
Traceback (most recent call last):
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 68, in main
    phalp_tracker = PHALP_Prime_TokenHMR(cfg)
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 50, in __init__
    super().__init__(cfg)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 53, in __init__
    self.setup_hmr()
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 53, in setup_hmr
    self.HMAR = TokenHMRPredictor(self.cfg)
  File "/home/lenovo/TokenHMR/tokenhmr/track.py", line 21, in __init__
    super().__init__(cfg)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/models/hmar/hmr.py", line 17, in __init__
    self.load_weights(cfg.hmr.hmar_path)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/models/hmar/hmr.py", line 23, in load_weights
    self.hmar_old.load_weights(path)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/phalp/models/hmar/hmar.py", line 47, in load_weights
    checkpoint_file = torch.load(path)
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/lenovo/miniconda3/envs/tkhmr/lib/python3.10/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Do you have similar problems or any clues to handle them? Sorry for bothering, cause it is a little hurried! I would appreciate it if you could reply to me.

Best regards,
Peilun
